config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'home#index'

  resources :passcodes, only: [:index, :new, :create]

end

app/models/item.rb
class Item < ActiveRecord::Base
  has_many :line_items

  [:name, :abbreviation].each do |field|
    validates field, presence: true, uniqueness: true
  end
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :item
  belongs_to :passcode

  validates_presence_of :item_id, :item_level, :passcode, :quantity

  def self.permitted_params
    [:item_id, :item_level, :quantity]
  end
end

app/models/passcode.rb
class Passcode < ActiveRecord::Base
  has_many :line_items, inverse_of: :passcode
  accepts_nested_attributes_for :line_items, reject_if: proc {|attributes| attributes[:item_id].blank? }

  validates :code, presence: true, uniqueness: true
  validates :ap, numericality: true
  validates :xm, numericality: true

  class << self
    def new_with_line_items
      new.tap {|passcode| passcode.line_items.build }
    end

    def permitted_params
      @permitted_params ||= [:code, :ap, :xm, {line_items_attributes: LineItem.permitted_params}]
    end

    def with_items
      includes line_items: :item
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :set_gettext_locale
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/passcodes_controller.rb
class PasscodesController < ApplicationController
  responders :flash, :collection

  def index
    @passcodes = Passcode.with_items
    respond_with @passcodes
  end

  def new
    @passcode = Passcode.new_with_line_items
  end

  def create
    @passcode = CreatePasscodeService.call params
    respond_with @passcode
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.haml
%p= _ 'Welcome to Passcoder!'
%p= link_to _('Enter passcode'), new_passcode_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= content_for?(:title) ? yield(:title) : _('Passcoder')
    %meta(charset='utf-8')
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    = google_webfonts_link_tag :coda
    = stylesheet_link_tag 'application'
    = stylesheet_link_tag params[:controller] if ::Rails.application.assets.find_asset("#{params[:controller]}.css")
    = javascript_include_tag 'vendor/modernizr'
    = javascript_include_tag 'application' # , 'data-turbolinks-track' => true
    = javascript_include_tag params[:controller] if ::Rails.application.assets.find_asset("#{params[:controller]}.js")
    = csrf_meta_tags
  %body
    .top-bar
      %h1= _('Passcoder')
    #flash
      %p.notice= notice
      %p.alert= alert
    = yield

app/views/passcodes/_passcode.html.haml
.passcode
  .code= passcode.code
  .ap= _('%{ap} AP') % {ap: passcode.ap}
  .xm= _('%{xm} XM') % {xm: passcode.xm}
  - passcode.line_items.each do |line_item|
    - abbreviation = line_item.item.abbreviation
    %div{class: "#{abbreviation.downcase}#{line_item.item_level}"}
      = line_item.quantity
      == #{abbreviation}#{line_item.item_level}

app/views/passcodes/index.html.haml
= render @passcodes

app/views/passcodes/new.html.haml
- if @passcode.errors.present?
  %p= _ 'Your passcode could not be saved because of the errors marked below.'

= form_for @passcode do |f|
  = f.input_div :code, label: _('Passcode')
  = f.input_div :ap, label: _('AP')
  = f.input_div :xm, label: _('XM')
  .line_item
    = f.fields_for :line_items, child_index: '' do |li|
      = render_cell :item_selector, :show, form: li
      = li.input_div :item_level, label: _('Level')
      = li.input_div :quantity
  .buttons
    .add_item= f.button _('Add item'), class: 'new_line_item', type: 'button'
    .save= f.submit _('Save')